// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: internal/rpc/proto/file.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListReposRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReposRequest) Reset() {
	*x = ListReposRequest{}
	mi := &file_internal_rpc_proto_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReposRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReposRequest) ProtoMessage() {}

func (x *ListReposRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReposRequest.ProtoReflect.Descriptor instead.
func (*ListReposRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_file_proto_rawDescGZIP(), []int{0}
}

type ListReposResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repos         []*RepoInfo            `protobuf:"bytes,1,rep,name=repos,proto3" json:"repos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReposResponse) Reset() {
	*x = ListReposResponse{}
	mi := &file_internal_rpc_proto_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReposResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReposResponse) ProtoMessage() {}

func (x *ListReposResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReposResponse.ProtoReflect.Descriptor instead.
func (*ListReposResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_file_proto_rawDescGZIP(), []int{1}
}

func (x *ListReposResponse) GetRepos() []*RepoInfo {
	if x != nil {
		return x.Repos
	}
	return nil
}

type RepoInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoInfo) Reset() {
	*x = RepoInfo{}
	mi := &file_internal_rpc_proto_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoInfo) ProtoMessage() {}

func (x *RepoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoInfo.ProtoReflect.Descriptor instead.
func (*RepoInfo) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_file_proto_rawDescGZIP(), []int{2}
}

func (x *RepoInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_internal_rpc_proto_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_file_proto_rawDescGZIP(), []int{3}
}

func (x *StatRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *StatRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ModTimeUnix   int64                  `protobuf:"varint,4,opt,name=mod_time_unix,json=modTimeUnix,proto3" json:"mod_time_unix,omitempty"`
	Mode          uint32                 `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_internal_rpc_proto_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_file_proto_rawDescGZIP(), []int{4}
}

func (x *StatResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StatResponse) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *StatResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StatResponse) GetModTimeUnix() int64 {
	if x != nil {
		return x.ModTimeUnix
	}
	return 0
}

func (x *StatResponse) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type ReadDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDirRequest) Reset() {
	*x = ReadDirRequest{}
	mi := &file_internal_rpc_proto_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDirRequest) ProtoMessage() {}

func (x *ReadDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDirRequest.ProtoReflect.Descriptor instead.
func (*ReadDirRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_file_proto_rawDescGZIP(), []int{5}
}

func (x *ReadDirRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *ReadDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*StatResponse        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDirResponse) Reset() {
	*x = ReadDirResponse{}
	mi := &file_internal_rpc_proto_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDirResponse) ProtoMessage() {}

func (x *ReadDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDirResponse.ProtoReflect.Descriptor instead.
func (*ReadDirResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_file_proto_rawDescGZIP(), []int{6}
}

func (x *ReadDirResponse) GetEntries() []*StatResponse {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        int64                  `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_internal_rpc_proto_file_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_file_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_file_proto_rawDescGZIP(), []int{7}
}

func (x *ReadRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *ReadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReadRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadRequest) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type ReadChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadChunk) Reset() {
	*x = ReadChunk{}
	mi := &file_internal_rpc_proto_file_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChunk) ProtoMessage() {}

func (x *ReadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_file_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChunk.ProtoReflect.Descriptor instead.
func (*ReadChunk) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_file_proto_rawDescGZIP(), []int{8}
}

func (x *ReadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SyncChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SyncChunk_Header
	//	*SyncChunk_File
	Payload       isSyncChunk_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncChunk) Reset() {
	*x = SyncChunk{}
	mi := &file_internal_rpc_proto_file_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncChunk) ProtoMessage() {}

func (x *SyncChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_file_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncChunk.ProtoReflect.Descriptor instead.
func (*SyncChunk) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_file_proto_rawDescGZIP(), []int{9}
}

func (x *SyncChunk) GetPayload() isSyncChunk_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SyncChunk) GetHeader() *SyncHeader {
	if x != nil {
		if x, ok := x.Payload.(*SyncChunk_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *SyncChunk) GetFile() *SyncFile {
	if x != nil {
		if x, ok := x.Payload.(*SyncChunk_File); ok {
			return x.File
		}
	}
	return nil
}

type isSyncChunk_Payload interface {
	isSyncChunk_Payload()
}

type SyncChunk_Header struct {
	Header *SyncHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type SyncChunk_File struct {
	File *SyncFile `protobuf:"bytes,2,opt,name=file,proto3,oneof"`
}

func (*SyncChunk_Header) isSyncChunk_Payload() {}

func (*SyncChunk_File) isSyncChunk_Payload() {}

type SyncHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	CommitMessage string                 `protobuf:"bytes,2,opt,name=commit_message,json=commitMessage,proto3" json:"commit_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncHeader) Reset() {
	*x = SyncHeader{}
	mi := &file_internal_rpc_proto_file_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncHeader) ProtoMessage() {}

func (x *SyncHeader) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_file_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncHeader.ProtoReflect.Descriptor instead.
func (*SyncHeader) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_file_proto_rawDescGZIP(), []int{10}
}

func (x *SyncHeader) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *SyncHeader) GetCommitMessage() string {
	if x != nil {
		return x.CommitMessage
	}
	return ""
}

type SyncFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Deleted       bool                   `protobuf:"varint,3,opt,name=deleted,proto3" json:"deleted,omitempty"`
	IsDir         bool                   `protobuf:"varint,4,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncFile) Reset() {
	*x = SyncFile{}
	mi := &file_internal_rpc_proto_file_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFile) ProtoMessage() {}

func (x *SyncFile) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_file_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFile.ProtoReflect.Descriptor instead.
func (*SyncFile) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_file_proto_rawDescGZIP(), []int{11}
}

func (x *SyncFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SyncFile) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SyncFile) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *SyncFile) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	GitCommitted  bool                   `protobuf:"varint,3,opt,name=git_committed,json=gitCommitted,proto3" json:"git_committed,omitempty"`
	GitCommitHash string                 `protobuf:"bytes,4,opt,name=git_commit_hash,json=gitCommitHash,proto3" json:"git_commit_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_internal_rpc_proto_file_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_file_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_file_proto_rawDescGZIP(), []int{12}
}

func (x *SyncResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SyncResponse) GetGitCommitted() bool {
	if x != nil {
		return x.GitCommitted
	}
	return false
}

func (x *SyncResponse) GetGitCommitHash() string {
	if x != nil {
		return x.GitCommitHash
	}
	return ""
}

var File_internal_rpc_proto_file_proto protoreflect.FileDescriptor

const file_internal_rpc_proto_file_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/rpc/proto/file.proto\x12\n" +
	"phantom.v1\"\x12\n" +
	"\x10ListReposRequest\"?\n" +
	"\x11ListReposResponse\x12*\n" +
	"\x05repos\x18\x01 \x03(\v2\x14.phantom.v1.RepoInfoR\x05repos\"\x1e\n" +
	"\bRepoInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"5\n" +
	"\vStatRequest\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x85\x01\n" +
	"\fStatResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\"\n" +
	"\rmod_time_unix\x18\x04 \x01(\x03R\vmodTimeUnix\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\rR\x04mode\"8\n" +
	"\x0eReadDirRequest\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"E\n" +
	"\x0fReadDirResponse\x122\n" +
	"\aentries\x18\x01 \x03(\v2\x18.phantom.v1.StatResponseR\aentries\"e\n" +
	"\vReadRequest\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06length\x18\x04 \x01(\x03R\x06length\"\x1f\n" +
	"\tReadChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"t\n" +
	"\tSyncChunk\x120\n" +
	"\x06header\x18\x01 \x01(\v2\x16.phantom.v1.SyncHeaderH\x00R\x06header\x12*\n" +
	"\x04file\x18\x02 \x01(\v2\x14.phantom.v1.SyncFileH\x00R\x04fileB\t\n" +
	"\apayload\"G\n" +
	"\n" +
	"SyncHeader\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12%\n" +
	"\x0ecommit_message\x18\x02 \x01(\tR\rcommitMessage\"c\n" +
	"\bSyncFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x18\n" +
	"\adeleted\x18\x03 \x01(\bR\adeleted\x12\x15\n" +
	"\x06is_dir\x18\x04 \x01(\bR\x05isDir\"\x8b\x01\n" +
	"\fSyncResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12#\n" +
	"\rgit_committed\x18\x03 \x01(\bR\fgitCommitted\x12&\n" +
	"\x0fgit_commit_hash\x18\x04 \x01(\tR\rgitCommitHash2\xd0\x02\n" +
	"\vFileService\x12H\n" +
	"\tListRepos\x12\x1c.phantom.v1.ListReposRequest\x1a\x1d.phantom.v1.ListReposResponse\x129\n" +
	"\x04Stat\x12\x17.phantom.v1.StatRequest\x1a\x18.phantom.v1.StatResponse\x12B\n" +
	"\aReadDir\x12\x1a.phantom.v1.ReadDirRequest\x1a\x1b.phantom.v1.ReadDirResponse\x128\n" +
	"\x04Read\x12\x17.phantom.v1.ReadRequest\x1a\x15.phantom.v1.ReadChunk0\x01\x12>\n" +
	"\tSyncFiles\x12\x15.phantom.v1.SyncChunk\x1a\x18.phantom.v1.SyncResponse(\x01B<Z:github.com/martinsuchenak/phantom/internal/rpc/proto;protob\x06proto3"

var (
	file_internal_rpc_proto_file_proto_rawDescOnce sync.Once
	file_internal_rpc_proto_file_proto_rawDescData []byte
)

func file_internal_rpc_proto_file_proto_rawDescGZIP() []byte {
	file_internal_rpc_proto_file_proto_rawDescOnce.Do(func() {
		file_internal_rpc_proto_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_rpc_proto_file_proto_rawDesc), len(file_internal_rpc_proto_file_proto_rawDesc)))
	})
	return file_internal_rpc_proto_file_proto_rawDescData
}

var file_internal_rpc_proto_file_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_rpc_proto_file_proto_goTypes = []any{
	(*ListReposRequest)(nil),  // 0: phantom.v1.ListReposRequest
	(*ListReposResponse)(nil), // 1: phantom.v1.ListReposResponse
	(*RepoInfo)(nil),          // 2: phantom.v1.RepoInfo
	(*StatRequest)(nil),       // 3: phantom.v1.StatRequest
	(*StatResponse)(nil),      // 4: phantom.v1.StatResponse
	(*ReadDirRequest)(nil),    // 5: phantom.v1.ReadDirRequest
	(*ReadDirResponse)(nil),   // 6: phantom.v1.ReadDirResponse
	(*ReadRequest)(nil),       // 7: phantom.v1.ReadRequest
	(*ReadChunk)(nil),         // 8: phantom.v1.ReadChunk
	(*SyncChunk)(nil),         // 9: phantom.v1.SyncChunk
	(*SyncHeader)(nil),        // 10: phantom.v1.SyncHeader
	(*SyncFile)(nil),          // 11: phantom.v1.SyncFile
	(*SyncResponse)(nil),      // 12: phantom.v1.SyncResponse
}
var file_internal_rpc_proto_file_proto_depIdxs = []int32{
	2,  // 0: phantom.v1.ListReposResponse.repos:type_name -> phantom.v1.RepoInfo
	4,  // 1: phantom.v1.ReadDirResponse.entries:type_name -> phantom.v1.StatResponse
	10, // 2: phantom.v1.SyncChunk.header:type_name -> phantom.v1.SyncHeader
	11, // 3: phantom.v1.SyncChunk.file:type_name -> phantom.v1.SyncFile
	0,  // 4: phantom.v1.FileService.ListRepos:input_type -> phantom.v1.ListReposRequest
	3,  // 5: phantom.v1.FileService.Stat:input_type -> phantom.v1.StatRequest
	5,  // 6: phantom.v1.FileService.ReadDir:input_type -> phantom.v1.ReadDirRequest
	7,  // 7: phantom.v1.FileService.Read:input_type -> phantom.v1.ReadRequest
	9,  // 8: phantom.v1.FileService.SyncFiles:input_type -> phantom.v1.SyncChunk
	1,  // 9: phantom.v1.FileService.ListRepos:output_type -> phantom.v1.ListReposResponse
	4,  // 10: phantom.v1.FileService.Stat:output_type -> phantom.v1.StatResponse
	6,  // 11: phantom.v1.FileService.ReadDir:output_type -> phantom.v1.ReadDirResponse
	8,  // 12: phantom.v1.FileService.Read:output_type -> phantom.v1.ReadChunk
	12, // 13: phantom.v1.FileService.SyncFiles:output_type -> phantom.v1.SyncResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_internal_rpc_proto_file_proto_init() }
func file_internal_rpc_proto_file_proto_init() {
	if File_internal_rpc_proto_file_proto != nil {
		return
	}
	file_internal_rpc_proto_file_proto_msgTypes[9].OneofWrappers = []any{
		(*SyncChunk_Header)(nil),
		(*SyncChunk_File)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_rpc_proto_file_proto_rawDesc), len(file_internal_rpc_proto_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_rpc_proto_file_proto_goTypes,
		DependencyIndexes: file_internal_rpc_proto_file_proto_depIdxs,
		MessageInfos:      file_internal_rpc_proto_file_proto_msgTypes,
	}.Build()
	File_internal_rpc_proto_file_proto = out.File
	file_internal_rpc_proto_file_proto_goTypes = nil
	file_internal_rpc_proto_file_proto_depIdxs = nil
}
